# kubectl create secret generic gcloud --from-file=creds=./creds.json -n cherrypick
# kubectl create secret generic cherrypick --from-file=config=./default.yml -n cherrypick
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.yaml
# helm upgrade --install cnpg --namespace cnpg-system --create-namespace cnpg/cloudnative-pg
# kubectl create secret -n cherrypick generic moderators --from-literal=ids=<id1>,<id2>,<id3>

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - cnpg.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  - issuer.yaml
  - ingress.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 20.3.0
    releaseName: redis-ha
    namespace: cherrypick
    valuesFile: redis-values.yaml
    includeCRDs: true
