apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cherrypick
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: redis
                operator: In
                values:
                  - "true"
      containers:
      - name: redis
        image: redis:7.2.4-alpine3.19
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cherrypick
  labels:
    name: redis
spec:
  selector:
    name: redis
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
