apiVersion: v1
kind: Secret
metadata:
  name: pgpass-secret
  namespace: cherrypick
type: Opaque
data:
  .pgpass: Y25wZy1yLmNoZXJyeXBpY2suc3ZjOjU0MzI6Y2hlcnJ5cGljazpwb3N0Z3JlczoxMjM0

---

apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auto
metadata:
  name: cnpg
  namespace: cherrypick
  labels:
    cnpg.io/reload: "true"
data:
  username: cG9zdGdyZXM=
  password: MTIzNA==
