apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: cherrypick
spec:
  storageClassName: ""
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: cherrypick
spec:
  storageClassName: ""
  claimRef:
    name: postgres-pvc
    namespace: cherrypick
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: cherrypick
spec:
  storageClassName: ""
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: cherrypick
spec:
  storageClassName: ""
  claimRef:
    name: redis-pvc
    namespace: cherrypick
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis
