services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: 'redis:7.2.4-alpine3.19'
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: 'postgres:16.3-alpine'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  cherrypick:
    restart: unless-stopped
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   endpoint_mode: vip
    image: 'juunini/cherrypick:latest'
    volumes:
      - ./volumes/cherrypick/.config/default.yml:/cherrypick/.config/default.yml
      - ./volumes/cherrypick/files:/cherrypick/files
      - ./volumes/cherrypick/creds.json:/cherrypick/creds.json
      - ./entrypoint.sh:/cherrypick/entrypoint.sh
    depends_on:
    - redis
    - postgres
    - nginx
    ports:
      - 3000:3000
    privileged: true

  inotify:
    container_name: inotify
    restart: unless-stopped
    image: 'juunini/gsutil-inotify:latest'
    volumes:
      - ./volumes/cherrypick/files:/monitoring
      - ./volumes/inotify/creds.json:/creds.json
    environment:
      - BUCKET_NAME=yodangang-express

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/certbot/data:/var/www/certbot:ro
      - ./volumes/certbot/conf:/etc/nginx/ssl:ro

  certbot_new:
    image: certbot/certbot:latest
    container_name: certbot_new
    restart: no
    command: certonly --webroot --webroot-path=/var/www/certbot --email juuni.ni.i@gmail.com --agree-tos --no-eff-email -d yodangang.express
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt:rw
      - ./volumes/certbot/logs:/var/log/letsencrypt:rw
      - ./volumes/certbot/data:/var/www/certbot:rw

  certbot_renew:
    image: certbot/certbot:latest
    container_name: certbot_renew
    restart: no
    command:  certonly --webroot -w /var/www/certbot --force-renewal --server https://acme-v02.api.letsencrypt.org/directory --cert-name yodangang.express
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt:rw
      - ./volumes/certbot/logs:/var/log/letsencrypt:rw
      - ./volumes/certbot/data:/var/www/certbot:rw
    depends_on:
      - nginx
