apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherrypick
  namespace: cherrypick-dev
spec:
  selector:
    matchLabels:
      name: cherrypick
  template:
    metadata:
      labels:
        name: cherrypick
    spec:
      containers:
      - name: cherrypick
        image: juunini/cherrypick:dev
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: config
          mountPath: /cherrypick/.config
          readOnly: true
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcp/creds.json
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
      volumes:
        - name: config
          secret:
            secretName: cherrypick
            items:
            - key: config
              path: default.yml
