apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirectscheme-dev
  namespace: cherrypick-dev
spec:
  redirectScheme:
    permanent: true
    scheme: https

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cherrypick-secure-dev
  namespace: cherrypick-dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev.yodangang.express`)
      kind: Rule
      services:
        - name: cherrypick
          port: 80
  tls:
    secretName: cherrypick-cert-dev

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cherryipck-redirect-dev
  namespace: cherrypick-dev
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dev.yodangang.express`)
      kind: Rule
      services:
        - name: cherrypick
          port: 80
      middlewares:
        - name: https-redirectscheme-dev
