apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dev
  namespace: cherrypick
spec:
  acme:
    email: juuni.ni.i@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key-dev
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cherrypick-cert-dev
  namespace: cherrypick
spec:
  commonName: dev.yodangang.express
  secretName: cherrypick-cert-dev
  dnsNames:
    - dev.yodangang.express
  issuerRef:
    kind: Issuer
    name: letsencrypt-dev
