# kubectl create secret generic gcloud --from-file=creds=./creds.json -n cherrypick
# kubectl create secret generic cherrypick --from-file=config=./default-dev.yml -n cherrypick

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volume.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # if need to cert-manager
  # https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.yaml
  # - issuer.yaml

