# kubectl create secret generic cherrypick --from-file=config=./default-dev.yml -n cherrypick-dev
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - issuer.yaml
  - ingress.yaml
  - volume.yaml
  - postgres.yaml
  - redis.yaml
