name: Build and Push Docker Image(arm64)

on:
  push:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./YodangangExpress.Dockerfile
          push: true
          tags: docker.io/juunini/cherrypick:${{ steps.vars.outputs.sha_short }}, docker.io/juunini/cherrypick:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64/v8
